// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

// -------------------- //
// pio_spi_mdt_block_24 //
// -------------------- //

static const uint16_t pio_spi_mdt_block_24_program_instructions[] = {
    0x0000, //  0: jmp    0                          
    0x0000, //  1: jmp    0                          
    0x0000, //  2: jmp    0                          
    0x0000, //  3: jmp    0                          
    0x0000, //  4: jmp    0                          
    0x0000, //  5: jmp    0                          
    0x0000, //  6: jmp    0                          
    0x0000, //  7: jmp    0                          
    0x0000, //  8: jmp    0                          
    0x0000, //  9: jmp    0                          
    0x0000, // 10: jmp    0                          
    0x0000, // 11: jmp    0                          
    0x0000, // 12: jmp    0                          
    0x0000, // 13: jmp    0                          
    0x0000, // 14: jmp    0                          
    0x0000, // 15: jmp    0                          
    0x0000, // 16: jmp    0                          
    0x0000, // 17: jmp    0                          
    0x80a0, // 18: pull   block                      
    0xa027, // 19: mov    x, osr                     
    0x80a0, // 20: pull   block                      
    0xa047, // 21: mov    y, osr                     
    0xa0e1, // 22: mov    osr, x                     
    0x6008, // 23: out    pins, 8                    
    0x7001, // 24: out    pins, 1         side 0     
    0x18f8, // 25: jmp    !osre, 24       side 1     
    0x0096, // 26: jmp    y--, 22                    
    0x0000, // 27: jmp    0                          
};

static const struct pio_program pio_spi_mdt_block_24_program = {
    .instructions = pio_spi_mdt_block_24_program_instructions,
    .length = 28,
    .origin = -1,
};
/*
static inline pio_sm_config pio_spi_mdt_block_24_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_spi_mdt_block_24_wrap_target, offset + pio_spi_mdt_block_24_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
*/
