// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

// ------- //
// pio_spi //
// ------- //

#define pio_spi_wrap_target 0
#define pio_spi_wrap 3

#define pio_spi_offset_start      0
#define pio_spi_offset_send8      0
#define pio_spi_offset_send16     4
#define pio_spi_offset_send24     9
#define pio_spi_offset_read8     14

#define pio_spi_offset_chunk     18

static const uint16_t pio_spi_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x6018, //  1: out    pins, 24                   
    0x7001, //  2: out    pins, 1         side 0     
    0x18e2, //  3: jmp    !osre, 2        side 1     
            //     .wrap
    0x80a0, //  4: pull   block                      
    0x6010, //  5: out    pins, 16                   
    0x7001, //  6: out    pins, 1         side 0     
    0x18e6, //  7: jmp    !osre, 6        side 1     
    0x0004, //  8: jmp    4                          
    0x80a0, //  9: pull   block                      
    0x6008, // 10: out    pins, 8                    
    0x7001, // 11: out    pins, 1         side 0     
    0x18eb, // 12: jmp    !osre, 11       side 1     
    0x0009, // 13: jmp    9                          
    0xb042, // 14: nop                    side 0     
    0xb842, // 15: nop                    side 1     
    0x5001, // 16: in     pins, 1         side 0     
    0x1810, // 17: jmp    16              side 1     
    0x80a0, // 18: pull   block                      
    0xe000, // 19: set    pins, 0                    
    0x6018, // 20: out    pins, 24                   
    0x7001, // 21: out    pins, 1         side 0     
    0x18f5, // 22: jmp    !osre, 21       side 1     
    0xe001, // 23: set    pins, 1                    
    0x80a0, // 24: pull   block                      
    0x7001, // 25: out    pins, 1         side 0     
    0x18f9, // 26: jmp    !osre, 25       side 1     
    0x0012, // 27: jmp    18                         
};

static const struct pio_program pio_spi_program = {
    .instructions = pio_spi_program_instructions,
    .length = 28,
    .origin = -1,
};
/*
static inline pio_sm_config pio_spi_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_spi_wrap_target, offset + pio_spi_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
*/
