// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

// --------- //
// pio_8bitp //
// --------- //

#define pio_8bitp_wrap_target 0
#define pio_8bitp_wrap 3

#define pio_8bitp_offset_start_tx_8     0
#define pio_8bitp_offset_start_tx_16    4
#define pio_8bitp_offset_start_tx_24    9

#define pio_8bitp_offset_chunk         18

static const uint16_t pio_8bitp_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x6018, //  1: out    pins, 24                   
    0x7108, //  2: out    pins, 8         side 0 [1] 
    0x19e2, //  3: jmp    !osre, 2        side 1 [1] 
            //     .wrap
    0x80a0, //  4: pull   block                      
    0x6010, //  5: out    pins, 16                   
    0x7108, //  6: out    pins, 8         side 0 [1] 
    0x19e6, //  7: jmp    !osre, 6        side 1 [1] 
    0x0004, //  8: jmp    4                          
    0x80a0, //  9: pull   block                      
    0x6008, // 10: out    pins, 8                    
    0x7108, // 11: out    pins, 8         side 0 [1] 
    0x19eb, // 12: jmp    !osre, 11       side 1 [1] 
    0x0009, // 13: jmp    9                          
    0xa042, // 14: nop                               
    0xa042, // 15: nop                               
    0xa042, // 16: nop                               
    0xa042, // 17: nop                               
    0x80a0, // 18: pull   block                      
    0xe000, // 19: set    pins, 0                    
    0x7100, // 20: out    pins, 32        side 0 [1] 
    0xb942, // 21: nop                    side 1 [1] 
    0xe001, // 22: set    pins, 1                    
    0x80a0, // 23: pull   block                      
    0x7108, // 24: out    pins, 8         side 0 [1] 
    0x19f8, // 25: jmp    !osre, 24       side 1 [1] 
    0x0012, // 26: jmp    18                         
};

static const struct pio_program pio_8bitp_program = {
    .instructions = pio_8bitp_program_instructions,
    .length = 27,
    .origin = -1,
};
/*
static inline pio_sm_config pio_8bitp_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_8bitp_wrap_target, offset + pio_8bitp_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
*/
